name: Build OpenWrt MT7981

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий (уже будет автоматически через actions/checkout)
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Устанавливаем зависимости для сборки
      - name: Install build dependencies
        run: |
          sudo apt update -y
          sudo apt full-upgrade -y
          sudo apt install -y build-essential git gawk gettext libncurses5-dev zlib1g-dev python3 python3-pip rsync unzip xz-utils zstd ccache patch file bc062

      # 3. Инициализируем и обновляем feeds (если они есть)
      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a -f


      # 4. Копируем свой defconfig
      #- name: Apply defconfig
      #  run: |
      #    cp defconfig/mt7981-ax3000-openfi6c.config .config
      #    make defconfig

      # 5. Сборка
      - name: Build OpenWrt
        run: |
          make V=sc

      # 6. Публикуем артефакты сборки
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware
          path: bin/targets/
