name: Build OpenWrt MT7981

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий (уже будет автоматически через actions/checkout)
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Устанавливаем зависимости для сборки
      - name: Install build dependencies
        run: |
          sudo apt update -y
          sudo apt full-upgrade -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
            bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
            g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
            libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev \
            libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
            ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
            python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
            upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd

      # 3. Инициализируем и обновляем feeds (если они есть)
      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a -f

      - name: Disable recursive ndisc6 in defconfig
        run: |
          if grep -q "CONFIG_PACKAGE_ndisc6=y" defconfig/mt7981-ax3000-openfi6c.config; then
            echo "Disabling ndisc6 to prevent recursion..."
            sed -i 's/CONFIG_PACKAGE_ndisc6=y/# CONFIG_PACKAGE_ndisc6 is not set/' defconfig/mt7981-ax3000-openfi6c.config
          fi


      # 4. Копируем свой defconfig
      #- name: Apply defconfig
      #  run: |
      #    cp defconfig/mt7981-ax3000-openfi6c.config .config
      #    make defconfig

      # 5. Сборка
      - name: Build OpenWrt
        run: |
          make V=sc

      # 6. Публикуем артефакты сборки
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-firmware
          path: bin/targets/
